apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkins
spec:
    replicas: 1
    selector:
        matchLabels:
            pod-type: jenkins
    template:
        metadata:
            name: jenkins
            labels:
                pod-type: jenkins
        spec:
            containers:
            -   name: vm-jenkins
                image: devops4me/jenkins:latest
                ports:
                -   containerPort: 8080
                -   containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
    name: jenkins
spec:
    ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 50000
      targetPort: 50000
      name: jnlp
    selector:
        pod-type: jenkins
