apiVersion: apps/v1
kind: Deployment
metadata:
    name: sonarqube
spec:
    replicas: 3
    selector:
        matchLabels:
            pod-type: sonarqube
    template:
        metadata:
            name: sonarqube
            labels:
                pod-type: sonarqube
        spec:
            containers:
            -   name: vm-sonarqube
                image: sonarqube:7.7-community
                env:
                -   name: sonar.jdbc.username
                    value: "sonar_rw_xyz123abc"
                -   name: sonar.jdbc.password
                    value: "xyzP23FSsd8ffa8So2bJw4so"
                -   name: sonar.jdbc.url
                    value: "jdbc:postgresql://sonardb/sonar_db_hyqlbi"
                ports:
                -   containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
    name: sonarqube
spec:
    ports:
    - port: 80
      targetPort: 9000
    selector:
        pod-type: sonarqube
